# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_auto_20171110_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
