# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0006_auto_20171110_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.Profile')),
            ],
        ),
    ]
