# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0007_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_title', models.TextField(blank=True, max_length=1500)),
                ('collaborator', models.CharField(blank=True, max_length=500)),
                ('collaborator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.Profile')),
            ],
        ),
    ]
