# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0008_publica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='research_interest',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('cse', 'CSE'), ('ece', 'ECE'), ('eee', 'EEE'), ('dod', 'DOD')], default='cse', max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
