# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0009_auto_20171115_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('DOD', 'DOD')], default='cse', max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
