# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0011_auto_20171115_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('current', models.BooleanField(default=False)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.Profile')),
            ],
        ),
    ]
