# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0013_auto_20171116_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
