# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0017_auto_20171117_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
