# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0018_auto_20171117_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fbprofile_photo',
            field=models.URLField(blank=True),
        ),
    ]
