# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0019_profile_fbprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interest_title', models.TextField(blank=True, max_length=1500)),
                ('research_interest_description', models.TextField(blank=True, max_length=20000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.Profile')),
            ],
        ),
    ]
