# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0019_profile_fbprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pic',
            field=models.ImageField(default='students_pic/no-img.jpg', upload_to='students_pic/'),
        ),
        migrations.AddField(
            model_name='students',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
