# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0020_research'),
        ('mywebsite', '0020_auto_20171118_1315'),
    ]

    operations = [
    ]
