# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0022_auto_20171128_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='prof_pic/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('MA', 'MA'), ('EEE', 'EEE'), ('DOD', 'DOD'), ('CL', 'CL'), ('CST', 'CST'), ('CE', 'CE'), ('HSS', 'HSS'), ('BSBE', 'BSBE'), ('PH', 'PH'), ('ME', 'ME')], default='CSE', max_length=4),
        ),
        migrations.AlterField(
            model_name='students',
            name='pic',
            field=models.ImageField(blank=True, upload_to='students_pic/'),
        ),
    ]
