# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0024_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='text',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
