# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0025_promotion_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mywebsite.Profile'),
        ),
    ]
