# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0027_auto_20171128_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='document',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
